### ISSUE TITLE
LUA conditions style

### ISSUE THREAD

**Issue by mklabs** [chadvandy/wh2_modding_res#3]
Hey,

Just a little issue to recommend a slight change to a script snippet I saw while reading through the chapters. It's really about styling, the snippet is not incorrect.

https://github.com/chadvandy/wh2_modding_res/blob/master/src/chapter_3_1_2.md

```lua
function example_script()
    if cm:is_new_game() == true then
        -- it's a new game, so it'll run this stuff here
    else
        -- it isn't a new game, so it'll run this stuff here
    end
end
```

`cm:is_new_game() == true` is imo too verbose, since `cm:is_new_game()` returns a boolean, it could be written

```lua
function example_script()
    if cm:is_new_game() then
        -- it's a new game, so it'll run this stuff here
    else
        -- it isn't a new game, so it'll run this stuff here
    end
end
```

I think it's better for the reader to use the shorter version so that he understands that `cm:is_new_game()` is a function that returns a boolean, and that boolean could be used directly as a condition. And that checking it against `== true` again is not strictly mandatory.

Really, it doesn't really matters, it's about style mostly. Your call ;)

**Comment by chadvandy** [comment]
Thanks for the suggestion. Had it written that way to keep things legible for newer peeps, since I hadn't yet covered return values and didn't want to do too much confusing nonsense. Gonna redo this entire section anyway, and move it all towards the end
